POST https://localhost:7213/auth/login
Content-Type: application/json

{
    "email":"test@test1111.com",
    "password":"1234567899"
}

###
POST https://localhost:7213/auth/login
Content-Type: application/json

{
    "email":"test@test.comq",
    "password":"1234567899"
}
